apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: flask-project
spec:
  containers:
  - name: mysql-client
    image: mysql:5.7
    command: ["sleep", "3600"]
    env:
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_DATABASE
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD
    # Optional: If you want to mount CA certs or connect securely, skip for now
  restartPolicy: Never
