apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: my-dockerhub-user/flask-app:latest   # replace with your image
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql.flask-project.svc.cluster.local"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
